imports:
    - { resource: types.yml }
    - { resource: constraints.yml }

twig:
    form_themes:
        - '@IDCIExtraForm/Form/fields.html.twig'
        - '@IDCIExtraForm/Form/extra_form_recaptcha.html.twig'
