imports:
    - { resource: types.yml }
    - { resource: constraints.yml }

twig:
    form_themes:
        - 'IDCIExtraFormBundle:Form:fields.html.twig'
        - 'IDCIExtraFormBundle:Form:extra_form_recaptcha.html.twig'
