services:

    # ExtraFormType

    idci_extra_form.type:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType
        arguments: [null]
        abstract: true

    idci_extra_form.type_handler:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeHandler

    # ExtraFormConstraint

    idci_extra_form.constraint_handler:
        class: IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintHandler