parameters:
    idci_extra_form.builder.class: IDCI\Bundle\ExtraFormBundle\Builder\ExtraFormBuilder


services:

    # ExtraFormType

    idci_extra_form.type:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType
        arguments: [null]
        abstract: true

    idci_extra_form.type_handler:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeHandler


    # ExtraFormConstraint

    idci_extra_form.constraint:
        class: IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraint
        arguments: [null]
        abstract: true

    idci_extra_form.constraint_handler:
        class: IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintHandler


    # ExtraFormConfigurator

    idci_extra_form.configurator:
        class: IDCI\Bundle\ExtraFormBundle\Configurator\ExtraFormConfigurator
        arguments: [null]
        abstract: true

    idci_extra_form.configurator.doctrine:
        class: IDCI\Bundle\ExtraFormBundle\Configurator\DoctrineExtraFormConfigurator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: idci_extra_form.configurator, alias: doctrine }


    # ExtraFormBuilder

    idci_extra_form.builder:
        class: %idci_extra_form.builder.class%
        arguments:
            - @idci_extra_form.type_handler
            - @idci_extra_form.constraint_handler


    # Form Types

    form.type.idci_extra_form.extra_form_builder:
        class: IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormBuilderType
        arguments: [@idci_extra_form.builder]
        tags:
            - { name: form.type, alias: extra_form_builder }

    form.type.idci_extra_form.json_textarea:
        class: IDCI\Bundle\ExtraFormBundle\Form\Type\JsonTextareaType
        tags:
            - { name: form.type, alias: json_textarea }
