services:

    idci_extra_form.type_handler:
        class: IDCI\ExtraFormBundle\Type\ExtraFormTypeHandler

    idci_extra_form.constraint_handler:
        class: IDCI\ExtraFormBundle\Constraint\ExtraFormConstraintHandler