services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Controllers
    IDCI\Bundle\ExtraFormBundle\Controller\:
        resource: '../../Controller'
        # apply some configuration to these services
        public: true
        tags: ['controller.service_arguments']

    # Events Subscriber

    IDCI\Bundle\ExtraFormBundle\Event\Subscriber\SerializerSubscriber:
        tags:
            - { name: jms_serializer.event_subscriber }

    # ExtraFormType

    IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeRegistry: ~
    IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeRegistryInterface: '@IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeRegistry'

    IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType:
        abstract: true
        arguments: [null]
    IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeInterface: '@IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType'

    # ExtraFormConstraint

    IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintRegistry: ~
    IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintRegistryInterface: '@IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintRegistry'

    IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraint:
        abstract: true
        arguments: [null]
    IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintInterface: '@IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraint'


    # ConfigurationFetcher

    IDCI\Bundle\ExtraFormBundle\Configuration\Fetcher\ConfigurationFetcher:
        abstract: true
    IDCI\Bundle\ExtraFormBundle\Configuration\Fetcher\ConfigurationFetcherInterface: '@IDCI\Bundle\ExtraFormBundle\Configuration\Fetcher\ConfigurationFetcher'

    IDCI\Bundle\ExtraFormBundle\Configuration\Fetcher\ConfigurationFetcherRegistry: ~

    #idci_extra_form.configuration.fetcher.doctrine:
    #    class: IDCI\Bundle\ExtraFormBundle\Configuration\Fetcher\DoctrineConfigurationFetcher
    #    arguments: ['@doctrine.orm.entity_manager']
    #    tags:
    #        - { name: idci_extra_form.configuration.fetcher, alias: doctrine }


    # ExtraFormBuilder

    IDCI\Bundle\ExtraFormBundle\Configuration\Builder\ExtraFormBuilder: ~
    IDCI\Bundle\ExtraFormBundle\Configuration\Builder\ExtraFormBuilderInterface: '@IDCI\Bundle\ExtraFormBundle\Configuration\Builder\ExtraFormBuilder'

    # Form type extensions

    IDCI\Bundle\ExtraFormBundle\Form\Extension\HelpMessageTypeExtension:
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    IDCI\Bundle\ExtraFormBundle\Form\Extension\HelpMessageTypeExtensionInterface: '@IDCI\Bundle\ExtraFormBundle\Form\Extension\HelpMessageTypeExtension'

    # Form Type Data Transformers

    IDCI\Bundle\ExtraFormBundle\Form\DataTransformer\UploadedFileToPathTransformer:
        arguments:
            $uploadsDir: '%idci_extra_form.working_dir%/uploaded_files'

    # Form Types

    IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormBuilderType:
        tags:
            - { name: form.type, alias: extra_form_builder }

    IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormCollectionType:
        tags:
            - { name: form.type, alias: extra_form_collection }

    IDCI\Bundle\ExtraFormBundle\Form\Type\FileType:
        tags:
            - { name: form.type, alias: extra_form_file }

    IDCI\Bundle\ExtraFormBundle\Form\Type\JsonTextareaType:
        tags:
            - { name: form.type, alias: extra_form_json_textarea }

    IDCI\Bundle\ExtraFormBundle\Form\Type\IbanTextType:
        tags:
            - { name: form.type, alias: extra_form_iban_text }

    IDCI\Bundle\ExtraFormBundle\Form\Type\IbanType:
        tags:
            - { name: form.type, alias: extra_form_iban }

    IDCI\Bundle\ExtraFormBundle\Form\Type\HtmlType:
        tags:
            - { name: form.type, alias: extra_form_html }

    IDCI\Bundle\ExtraFormBundle\Form\Type\RangeType:
        tags:
            - { name: form.type, alias: extra_form_range }

    IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormTypeChoiceType:
        tags:
            - { name: form.type, alias: extra_form_type_choice }

    IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormConstraintChoiceType:
            tags:
                - { name: form.type, alias: extra_form_constraint_choice }

    IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormEditorType:
        tags:
            - { name: form.type, alias: extra_form_editor }
            - { name: idci_asset_loader.asset_provider, alias: extra_form_editor }

    IDCI\Bundle\ExtraFormBundle\Form\Type\TagsType:
        tags:
            - { name: form.type, alias: extra_form_tags }

