parameters:
    idci_extra_form.builder.class: IDCI\Bundle\ExtraFormBundle\Builder\ExtraFormBuilder


services:

    # ExtraFormType

    idci_extra_form.type_registry:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormTypeRegistry

    idci_extra_form.type:
        class: IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType
        arguments: [null]
        abstract: true


    # ExtraFormConstraint

    idci_extra_form.constraint_registry:
        class: IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraintRegistry

    idci_extra_form.constraint:
        class: IDCI\Bundle\ExtraFormBundle\Constraint\ExtraFormConstraint
        arguments: [null]
        abstract: true


    # ConfigurationBuilder

    idci_extra_form.configuration_builder_registry:
        class: IDCI\Bundle\ExtraFormBundle\Builder\ConfigurationBuilderRegistry

    idci_extra_form.configuration_builder:
        class: IDCI\Bundle\ExtraFormBundle\Builder\ConfigurationBuilder
        arguments: [null]
        abstract: true

    #idci_extra_form.configuration_builder.doctrine:
    #    class: IDCI\Bundle\ExtraFormBundle\Builder\DoctrineConfigurationBuilder
    #    arguments: [@doctrine.orm.entity_manager]
    #    tags:
    #        - { name: idci_extra_form.configuration_builder, alias: doctrine }


    # ExtraFormBuilder

    idci_extra_form.builder:
        class: %idci_extra_form.builder.class%
        arguments:
            - @form.factory
            - @idci_extra_form.configuration_builder_registry
            - @idci_extra_form.type_registry
            - @idci_extra_form.constraint_registry


    # Form Types

    form.type.idci_extra_form.extra_form_builder:
        class: IDCI\Bundle\ExtraFormBundle\Form\Type\ExtraFormBuilderType
        arguments: [@idci_extra_form.builder]
        tags:
            - { name: form.type, alias: extra_form_builder }

    form.type.idci_extra_form.json_textarea:
        class: IDCI\Bundle\ExtraFormBundle\Form\Type\JsonTextareaType
        tags:
            - { name: form.type, alias: json_textarea }
