language: php

env:
    DOCKER_COMPOSE_VERSION: 1.16.0

sudo: required

services:
  - docker

php:
  - '5.6'

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

  - docker-compose build >> /dev/null

  - docker-compose run --rm php composer install --prefer-source --no-interaction --dev >> /dev/null
  - docker-compose run --rm node npm install --loglevel error

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make phpunit
  - make phpcs
  - make karma options='--single-run'

notifications:
    on_success: never
    on_failure: always
