language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

notifications:
    on_success: never
    on_failure: always
