version: '2'

services:

  node:
    image: idci-extra-form-editor/node:8.4.1-stretch
    build:
      context: .docker/build/node
    volumes:
      - ./:/usr/src/app

  php:
    image: idci-extra-form-editor/php:7.2-fpm
    build:
      context: .docker/build/php
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer

volumes:
  composer-cache: ~
