version: '2'

services:

  node:
    image: idci-extra-form-editor/node:8.4.1-stretch
    build:
      context: .docker/build/node
    volumes:
      - ./:/usr/src/app
      - composer-cache:/root/.composer

  php:
    image: idci-extra-form-editor/php:5.6-fpm
    build:
      context: .docker/build/php
      dockerfile: Dockerfile-5.6
    volumes:
      - ./:/var/www/html

volumes:
  composer-cache: ~
