IDCI\Bundle\ExtraFormBundle\Entity\ConfiguredType:

    exclusion_policy: ALL

    properties:
        id:
            expose: false
        name:
            expose: true
        configuration:
            expose: true
