IDCI\Bundle\ExtraFormBundle\Model\ConfiguredType:

    accessor_order: custom
    custom_accessor_order: [name, tags]

    exclusion_policy: ALL

    properties:
        name:
            expose: true
        tags:
            expose: true

    virtual_properties:
        getIcon:
            serialized_name: icon
        getDescription:
            serialized_name: description
        getFormType:
            serialized_name: form_type
        getFormTypeName:
            serialized_name: form_type_name
        getExtraFormOptions:
            serialized_name: extra_form_options
        getExtraFormConstraints:
            serialized_name: extra_form_constraints
