IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType:

    accessor_order: custom
    custom_accessor_order: [name, description, abstract, formType]

    exclusion_policy: ALL

    properties:
        name:
            expose: true
        formType:
            expose: true
            serialized_name: form_type
        description:
            expose: true
        abstract:
            expose: true

    virtual_properties:
        getIcon:
            serialized_name: icon
        getExtraFormOptions:
            serialized_name: extra_form_options
