IDCI\Bundle\ExtraFormBundle\Type\ExtraFormType:

    accessor_order: custom
    custom_accessor_order: [name, description, abstract, formType]

    exclusion_policy: ALL

    properties:
        className:
            expose: true
            serialized_name: form_type
        description:
            expose: true
        parent:
            expose: true
        extraFormOptions:
            expose: true
            serialized_name: extra_form_options
        extraFormConstraints:
            expose: true
            serialized_name: extra_form_constraints
