version: '2'

services:

  php:
    image: idci-extra-form-editor/php:7.2-fpm
    build:
      context: ./php
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer

volumes:
  composer-cache: ~
